version: '3'

services:
  # 1. THE REVERSE PROXY
  # This listens on ports 80/443 and routes traffic to your app
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # 2. THE SSL COMPANION
  # This handles the Let's Encrypt automation
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=wadeea@strefqa.com
  # 3. YOUR FLUTTER APP
flutter-app:
  build:
    context: .. # Move context UP one level so it can see 'mobile'
    dockerfile: ./Dockerfile # Point back to where the Dockerfile actually is

  container_name: wadeea-web
  restart: always
  environment:
    - VIRTUAL_HOST=waddea.strefqa.com,www.wadeea.strefqa.com
    - LETSENCRYPT_HOST=waddea.strefqa.com,www.wadeea.strefqa.com
volumes:
  certs:
  vhost:
  html:
  acme:
